version: '2.3'
services:
  service1:
    build:
      context: ./apps/service1
      dockerfile: ./Dockerfile
    image: service1

  service2:
    build:
      context: ./apps/service2
      dockerfile: ./Dockerfile
    image: service2

  service3:
    build:
      context: ./apps/service3
      dockerfile: ./Dockerfile
    image: service3
