version: '2.3'
services:
  service1:
    build:
      context: ./apps/service1
      dockerfile: ./Dockerfile
    image: service1

  service2:
    build:
      context: ./apps/service2
      dockerfile: ./Dockerfile
    image: service2

  service3:
    build:
      context: ./apps/service3
      dockerfile: ./Dockerfile
    image: service3

  nextjs:
    build:
      context: ./apps/nextjs
      dockerfile: ./Dockerfile
    image: nextjs
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: mysql://root:root@host.docker.internal:3306/nextjs

  db:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4
    restart: always
    ports:
      - 3306:3306
    volumes:
      - 'db:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

volumes:
  db:
