name: Sleep test 2
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, linux]
    steps:
      - run: echo "sleep1します"
      - run: sleep 60
      - run: echo "sleep2します"
      - run: sleep 60
      - run: echo "sleep3します"
      - run: sleep 60
      - run: echo "sleep4します"
      - run: sleep 60
      - run: echo "sleep5します"
      - run: sleep 60
      - run: echo "sleep6します"
      - run: sleep 60
      - run: echo "sleep7します"
      - run: sleep 60
      - run: echo "sleep8します"
      - run: sleep 60
      - run: echo "sleep9します"
      - run: sleep 60
      - run: echo "sleep10します"
      - run: sleep 60
