name: pull request comment
on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited]

jobs:
  echo_inputs:
    name: echo inputs
    runs-on: ubuntu-latest
    steps:
      - run: echo "event - ${{ toJSON(github.event) }}"

  deploy1:
    if: github.event_name == 'issue_comment' &&
        contains(github.event.comment.html_url, '/pull/') && 
        startsWith(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "deploy1:  (${{ github.event.comment.body }})"
      
  deploy2:
    if: (github.event.issue.pull_request != null) && github.event.comment.body == '!github deploy-feature'
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "deploy2:  (${{ github.event.comment.body }})"
