name: Check base branch

on:
  pull_request:
    types: [opened, reopened, edited, synchronize, ready_for_review]

jobs:
  check:
    name: Check base branch
    runs-on: [self-hosted, '${{ github.run_id }}', 'runs-on=FARGATE_SPOT']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: echo branch of PR
        run: |
          echo "Base branch of PR: ${{ github.base_ref }}"
          echo "Head branch of PR: ${{ github.head_ref }}"

      - name: echo branch SHA
        run: |
          echo "Base branch SHA: ${{ github.event.pull_request.head.sha }}"
          echo "Head branch SHA: ${{ github.event.pull_request.base.sha }}"

      - name: Check branches
        run: |
          HEAD_SHA=${{ github.event.pull_request.head.sha }}
          BASE_SHA=${{ github.event.pull_request.base.sha }}
          COMMON_ANCESTOR_SHA=$(git merge-base $HEAD_SHA $BASE_SHA)

          echo "common ancestor SHA: $COMMON_ANCESTOR_SHA"

          if [[ "$COMMON_ANCESTOR_SHA" == "$BASE_SHA" ]]; then
            echo "The base branch of the PR is the branch from which the head branch was created."
          else
            echo "The base branch of the PR is not the branch from which the head branch was created."
            exit 1
          fi

      - name: Post check failure to Pull Request
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':warning:マージ先のブランチを間違えている可能性があります\n' +
                'There's a possibility that the base branch of the PR is incorrect.'
            })
