name: Check base branch
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize, ready_for_review]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - run: git show-branch

      - name: Get base branch
        run: |
          BASE_BRANCH=$(git show-branch | grep '*' | grep -v '$(git rev-parse --abbrev-ref HEAD)' | head -1 | awk -F'[]~^[]' '{print $2}')
          echo "BASE_BRANCH=${BASE_BRANCH}" >> $GITHUB_ENV

      - name: echo
        run: |
          echo ${GITHUB_BASE_REF}
          echo ${BASE_BRANCH}

      - name: Check base branch
        run: ${GITHUB_BASE_REF} === ${BASE_BRANCH}
