name: Check base branch

on:
  pull_request:
    types: [opened, reopened, edited, synchronize, ready_for_review]

jobs:
  check:
    name: Check base branch
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: echo branch of PR
        run: |
          echo "Base branch of PR: ${{ github.base_ref }}"
          echo "Head branch of PR: ${{ github.head_ref }}"

      - name: echo branch SHA
        run: |
          echo "Base branch SHA: ${{ github.event.pull_request.head.sha }}"
          echo "Head branch SHA: ${{ github.event.pull_request.base.sha }}"

      - name: Check if PR branch is behind base branch
        id: behind_check
        uses: actions/github-script@v6
        with:
          script: |
            const pr_number = context.issue.number
            console.log(pr_number)
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            })
            console.log(pr)
            const { data: compare } = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: pr.base.sha,
              head: pr.head.sha
            })
            console.log(compare)
            return compare.behind_by === 0

      - name: Check branches
        id: check_branches
        if: ${{ steps.behind_check.outcome == 'success' }}
        run: |
          HEAD_SHA=${{ github.event.pull_request.head.sha }}
          BASE_SHA=${{ github.event.pull_request.base.sha }}
          COMMON_ANCESTOR_SHA=$(git merge-base $HEAD_SHA $BASE_SHA)

          echo "common ancestor SHA: $COMMON_ANCESTOR_SHA"

          if [[ "$COMMON_ANCESTOR_SHA" == "$BASE_SHA" ]]; then
            echo "The base branch of the PR is the branch from which the head branch was created."
          else
            echo "The base branch of the PR is not the branch from which the head branch was created."
            exit 1
          fi

      - name: Post check failure to Pull Request
        if: ${{ steps.check_branches.outcome == 'failure' }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## :warning: マージ先のブランチを間違えている可能性があります！\n' +
                'There\'s a possibility that the base branch of the PR is incorrect.'
            })
