name: service2
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - '**/apps/service2/**'

env:
  SERVICE_NAME: service2

jobs:
  npm_test:
    name: Yarn test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nodejs and npm
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci
        working-directory: apps/${SERVICE_NAME}

      - name: npm test
        run: npm test
        working-directory: apps/${SERVICE_NAME}

  docker_build:
    name: Docker build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Build
        run: docker-compose build ${SERVICE_NAME}
