name: CodeceptJS Test

on:
  workflow_dispatch:

jobs:
  codeceptjs_test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Build
        run: docker-compose build
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1

      - name: Docker Run
        run: docker-compose up -d nextjs

      - name: Install Dependencies
        run: npm install
        working-directory: codeceptjs

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: run CodeceptJS tests
        run: npm run codeceptjs
        working-directory: codeceptjs
