name: Delete Workflow Runs
on:
  workflow_dispatch:

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            }).then(({ data }) => {
              data.workflow_runs.forEach(workflow_run => {
                octokit.rest.actions.deleteWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: workflow_run.id
                });
              });
            });
        env:
          GITHUB_TOKEN: ${{ secrets.MY_ACCESS_TOKEN  }}
