name: Post to Pull Request
on:
  workflow_dispatch:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  post-to-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Echo GitHub Parameter
        run: echo "${{ toJSON(github) }}"

      - name: Post to Pull Request
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '**aaaaaaaaaaaa!!**\n' +
                '- aaaaaaaaaaa\n' +
                '    - https://www.google.com\n' +
                '\n' +
                '👇\n' +
                'https://www.google.com'
            })
