name: Workflow Run Pruner

on:
  workflow_dispatch:

jobs:
  prune:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

      - name: ✂ Remove runs of the cleanup workflow itself
        uses: actions/github-script@v4 # https://github.com/actions/github-script
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pages = 5;

            let runs_to_delete = [];

            for (let page = 0; page < pages; page += 1) {
              let response = await github.actions.listWorkflowRuns({
                owner: context.repo.owner,
                page: page,
                per_page: 100,
                repo: context.repo.repo,
                workflow_id: 'workflow_run_pruner.yml'
              });

              if (response.data.workflow_runs.length > 0) {
                for (const run of response.data.workflow_runs) {
                    runs_to_delete.push([run.id, run.name]);
                }
              }
            }
