name: Self Hosted Runner (WebHook)
on:
  workflow_dispatch:

jobs:
  echo-github-parameter:
    runs-on: [self-hosted, "${{ github.run_id }}", "runs-on=FARGATE_SPOT"]
    timeout-minutes: 60
    steps:
      - name: Echo GitHub Parameter
        run: echo "${{ toJSON(github) }}"

      - name: Echo Runner OS
        run: echo "${{ runner.os }}"

      - name: sleep
        run: |
          echo "sleepします"
          sleep 5

  echo-github-parameter2:
    runs-on: [self-hosted, "${{ github.run_id }}", "runs-on=FARGATE_SPOT", "type=MEDIUM"]
    timeout-minutes: 60
    steps:
      - name: Echo GitHub Parameter
        run: echo "${{ toJSON(github) }}"

      - name: Echo Runner OS
        run: echo "${{ runner.os }}"

      - name: sleep
        run: |
          echo "sleepします"
          sleep 5

  echo-github-parameter3:
    runs-on: [self-hosted, "${{ github.run_id }}", "runs-on=FARGATE_SPOT", "type=LARGE"]
    timeout-minutes: 60
    steps:
      - name: Echo GitHub Parameter
        run: echo "${{ toJSON(github) }}"

      - name: Echo Runner OS
        run: echo "${{ runner.os }}"

      - name: sleep
        run: |
          echo "sleepします"
          sleep 5

  echo-github-parameter4:
    runs-on: [self-hosted, "${{ github.run_id }}", "runs-on=CODEBUILD"]
    timeout-minutes: 60
    steps:
      - name: Echo GitHub Parameter
        run: echo "${{ toJSON(github) }}"

      - name: Echo Runner OS
        run: echo "${{ runner.os }}"

      - name: Echo env
        run: printenv

      - name: sleep
        run: |
          echo "sleepします"
          sleep 5
