name: Echo Parameter
on:
  workflow_dispatch:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  deploy-actions-dummy:
    runs-on: [self-hosted, my-runner]
    steps:
      - name: Echo Parameter
      - run: echo "${{ toJSON(github) }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: sleep1
        run: |
          echo "sleepします"
          sleep 5
