name: Self Hosted Runner Test
on:
  workflow_dispatch:

jobs:
  self-hosted-runner-test:
    runs-on: [self-hosted, my-runner]
    steps:
      - name: Echo GitHub Parameter
      - run: echo "${{ toJSON(github) }}"

      - name: Echo Runner OS
      - run: echo "${{ runner.os }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: sleep1
        run: |
          echo "sleepします"
          sleep 5
