name: Services Migration
on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: Deploy target
        options:
          - dev
          - e2e
      migration_data:
        type: choice
        description: Migration Data
        options:
          - dev
          - e2e
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      migration_data:
        required: true
        type: string

jobs:
  deploy-actions-dummy:
    # runs-on: [self-hosted, linux]
    runs-on: ubuntu-latest
    steps:
      - run: echo "event - ${{ toJSON(inputs) }}"

      - run: echo "event - ${{ toJSON(github) }}"

      - run: echo "sleep1します"
      - run: sleep 60

      - run: echo "sleep2します"
      - run: sleep 60
