name: Services CD
on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: Deploy target
        options:
          - dev
          - e2e
  push:
    branches:
      - master
    paths:
      - "apps/service1/**"

jobs:
  deploy-actions-dummy:
    # runs-on: [self-hosted, linux]
    runs-on: ubuntu-latest
    steps:
      - run: echo "event - ${{ toJSON(inputs) }}"

      - run: echo "event - ${{ toJSON(github) }}"

      - run: echo "sleep1します"
      - run: sleep 60

      - run: echo "sleep2します"
      - run: sleep 60
