name: Services Migration
on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: Deploy target
        options:
          - dev
          - e2e
      migration_data:
        type: choice
        description: Migration Data
        options:
          - dev
          - e2e

jobs:
  deploy-actions-dummy:
    runs-on: [self-hosted, linux]
    steps:
      - run: $(echo '${{ toJSON(github) }}' | jq )

      - run: echo "sleep1します"
      - run: sleep 60

      - run: echo "sleep2します"
      - run: sleep 60
