name: Service1 CI
on:
  workflow_dispatch:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths:
      - "apps/service1/**"
  issue_comment:
    types: [created, edited]
    
jobs:
  deploy-actions-dummy:
    # runs-on: [self-hosted, linux]
    runs-on: ubuntu-latest
    steps:
      - run: echo "event - ${{ toJSON(inputs) }}"

      - run: echo "event - ${{ toJSON(github) }}"

      - run: echo "sleep1します"
      - run: sleep 5

      - run: echo "sleep2します"
      - run: sleep 5

      - name: Post preview URL to Pull Request
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '**aaaaaaaaaaaa!!**\n' +
                '- aaaaaaaaaaa\n' +
                '    - https://www.google.com\n' +
                '\n' +
                'パスワードはこちら👇\n' +
                'https://www.google.com'
            })
